/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/threeD/cozy-lvr.glb 
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cozy-modern-living-room-6a030bdb839e4e74bb58d7edb8f329e7
Title: Cozy Modern Living Room
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cozy(props) {
  const { nodes, materials } = useGLTF("/threeD/cozy-lvr.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.296}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-99.684, -16.617, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={800}
          >
            <mesh
              geometry={nodes.Modern_Living_Room_Structure_Windows_0.geometry}
              material={materials.Structure_Windows}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_1.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_2.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_3.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_4.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_5.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_6.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_7.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_8.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_9.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_10.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_11.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_12.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_13.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_14.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_15.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_16.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_17.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_18.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_19.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_20.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_21.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_22.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_23.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_24.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_25.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_26.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Carpet_0_27.geometry}
              material={materials.Carpet}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_EndTable_0.geometry}
              material={materials.EndTable}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Light_0.geometry}
              material={materials.Light}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Lamp_0.geometry}
              material={materials.Lamp}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_CoffeeTable_0.geometry}
              material={materials.CoffeeTable}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Bowl_0.geometry}
              material={materials.Bowl}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Pot_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_PlantBranch_0.geometry}
              material={materials.PlantBranch}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_PlantLeaves_0.geometry}
              material={materials.PlantLeaves}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Structure_0.geometry}
              material={materials.Structure}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_EndTable_Glass_0.geometry}
              material={materials.EndTable_Glass}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Sofa_0.geometry}
              material={materials.Sofa}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Backdrop_0.geometry}
              material={materials.Backdrop}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_TV_0.geometry}
              material={materials.material_14}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Shelf_0.geometry}
              material={materials.Shelf}
            />
            <mesh
              geometry={nodes.Modern_Living_Room_Painting_0.geometry}
              material={materials.Painting}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/threeD/cozy-lvr.glb");
